### ISSUE TITLE
Speed up method calls with a vector of function pointers

### ISSUE THREAD

**Issue by seven1m** [seven1m/natalie#11]
Consider the following Ruby code:

```ruby
class Foo
  def foo
    'foo'
  end

  def go
    10_000.times { foo }
  end
end

Foo.new.go
```

The "foo" method is looked up in the `methods` hashmap 10,000 times, even though the compiler could already have all the information it needed to compile that code into direct function calls.

When profiling code compiled with Natalie, method hashmap lookup is a considerable amount of time spent, sometimes 30% or more. For methods known at compile time, this could be much faster.

Basics:

1. The compiler keeps track of methods defined on classes.
2. In addition to being added to the methods hashmap, add the method pointer to a Vector.
3. The symbol "foo" can be turned into an index into the Vector, 0, 1, 2, ...

Of course, this would only work for method names known at compile time. For other cases, we'd still fall back to a hash lookup (the current technique).

It may not be this easy, but I think it's worth looking into!

**Comment by alimpfard** [comment]
Currently, it doesn't look like the compiler knows anything about the classes and their relations (correct me if I'm wrong, I didn't check too thoroughly), so not a whole lot would be known at compile time.
I briefly thought about this, here's what I came up with, given what I know of Ruby's runtime/class model:

- in any given expression, we need to know the type/class of `self`
- we need to track classes, and methods defined on them, especially the generated bindings
- some sort of type inference would be nice, though it'd be more of a type constraining system, given Ruby's model of execution
- we will be forced to fallback to dynamic dispatch, so a way to constrain those would be immensely helpful (probably a problem for much later, if ever)

Considering your example, the compiler needs to know that `self` is a `Foo` inside that block, and that involves knowing that `Integer.times` doesn't do any shenanigans with `instance_eval` or equivalent (this can be ignored for the time being), and only then can it safely determine what `foo` is referring to.

Once we have this info, that call to `foo` can be turned to a c++ call to `Foo_foo` (the mangled names are so nice here...), and even possibly inlined.

So, with all that, I think we need a type inference pass to resolve this issue.

Sorry for the 50 million word essay :P

**Comment by seven1m** [comment]
Great insight! You are correct about the compiler -- it needs to keep track of quite a bit more information than it does currently. Thanks for spelling out the steps here; that certainly helps us break the task into smaller chunks, i.e. teaching the compiler to infer types would be a good first step.

**Comment by seven1m** [comment]
I'm closing this, as it's not a well-defined task. We need some baby steps in the compiler before we can get here, namely type inference.
