### ISSUE TITLE
Hash cannot be used after calling `Hash#each` and returning inside the block

### ISSUE THREAD

**Issue by richardboehme** [seven1m/natalie#168]
The following program throws a `RuntimeException`:

```ruby
a = { a: 2 }
a.first
a[:b] = 1
```

When using `Hash#first` the Enumerable method `first` is called with looks like this (shortened):

```ruby
def first
  each do |arg|
    return arg
  end
end
```

If you try to insert a value to the hash, it will fail because `m_is_iterating` is still set to `true`. When returning in such a case we throw a LocalJumpError and rescue it. This means the macro block handler that hash uses (`NAT_RUN_BLOCK_AND_POSSIBLY_BREAK_WHILE_ITERATING_HASH`) does not know that it stopped iterating. I guess a simple fix would be to rescue the local jump error when running the block?

However, I'm not sure if "normal" block execution macros also need to handle this and if my proposed solution is the most elegant way of doing it...

**Comment by seven1m** [comment]
I think our new Defer might help with this. I'll work on it!

**Comment by richardboehme** [comment]
That sounds great! Could we even get rid of `NAT_RUN_BLOCK_AND_POSSIBLY_BREAK_WHILE_ITERATING_HASH` with this?

**Comment by seven1m** [comment]
Hope so!
