### ISSUE TITLE
Implement the Enumerable module

### ISSUE THREAD

**Issue by seven1m** [seven1m/natalie#19]
I started work in 2508f404717945e5fc8f6eac2649b3126bfd8528 on the Enumerable module. It's a biggie! Anyone is welcome to jump in and lend a hand!

Here are the specs that need to be enabled and passing:

- [x] all_spec.rb
- [x] any_spec.rb
- [x] chain_spec.rb
- [x] chunk_spec.rb
- [x] chunk_while_spec.rb
- [x] collect_concat_spec.rb
- [x] collect_spec.rb
- [x] count_spec.rb
- [x] cycle_spec.rb
- [x] detect_spec.rb
- [x] drop_spec.rb
- [x] drop_while_spec.rb
- [x] each_cons_spec.rb
- [x] each_entry_spec.rb
- [x] each_slice_spec.rb
- [x] each_with_index_spec.rb
- [x] each_with_object_spec.rb
- [x] entries_spec.rb
- [x] filter_map_spec.rb
- [x] filter_spec.rb
- [x] find_all_spec.rb
- [x] find_index_spec.rb
- [x] find_spec.rb
- [x] first_spec.rb
- [x] flat_map_spec.rb
- [x] grep_spec.rb
- [x] grep_v_spec.rb
- [x] group_by_spec.rb
- [x] include_spec.rb
- [x] inject_spec.rb
- [x] lazy_spec.rb
- [x] map_spec.rb
- [x] max_by_spec.rb
- [x] max_spec.rb
- [x] member_spec.rb
- [x] min_by_spec.rb
- [x] minmax_by_spec.rb
- [x] minmax_spec.rb
- [x] min_spec.rb
- [x] none_spec.rb
- [x] one_spec.rb
- [x] partition_spec.rb
- [x] reduce_spec.rb
- [x] reject_spec.rb
- [x] reverse_each_spec.rb
- [x] select_spec.rb
- [x] slice_after_spec.rb
- [x] slice_before_spec.rb
- [x] slice_when_spec.rb
- [x] sort_by_spec.rb
- [x] sort_spec.rb
- [x] sum_spec.rb
- [x] take_spec.rb
- [x] take_while_spec.rb
- [x] tally_spec.rb
- [x] to_a_spec.rb
- [x] to_h_spec.rb
- [x] uniq_spec.rb
- [x] zip_spec.rb

**Comment by seven1m** [comment]
@richardboehme you are a machine! The last remaining spec, `lazy_spec.rb`, seems a little light on details... If you have an idea of what to do there from the Ruby docs, then I say just do your best. I have never used Enumerator::Lazy in my years of using Ruby, so I don't think I could do any better. (But if you want me to take that one, just let me know.)

**Comment by richardboehme** [comment]
> @richardboehme you are a machine! The last remaining spec, `lazy_spec.rb`, seems a little light on details... If you have an idea of what to do there from the Ruby docs, then I say just do your best. I have never used Enumerator::Lazy in my years of using Ruby, so I don't think I could do any better. (But if you want me to take that one, just let me know.)

Thanks! I guess I'm going to look into `Enumerator::Lazy` in the next days 😄

**Comment by richardboehme** [comment]
I guess we can close this now, right? @seven1m

**Comment by seven1m** [comment]
Yep! :tada:
