### ISSUE TITLE
Issue with processing default arguments with an argument splat

### ISSUE THREAD

**Issue by richardboehme** [seven1m/natalie#60]
After playing around a bit with implementing some more Enumerable methods I think I found a natalie bug with the handling of default arguments. The following code prints 2 in Ruby and 1 in Natalie:

```ruby
def foo(a = 1, *args)
  puts a
end
foo(2)
```

I tried to understand where to look for this issue but I did not really find the position where this issue occurs. Maybe a small hint could help me finding the issue here :^)

**Comment by seven1m** [comment]
Good find!

The argument handling is mostly confined to these two files:

- https://github.com/seven1m/natalie/blob/master/lib/natalie/compiler/method_args.rb
- https://github.com/seven1m/natalie/blob/4a62b9d269679bde8f8ab89b54ae4e2b033cdd3e/src/natalie.cpp#L99-L175

With tests here:

https://github.com/seven1m/natalie/blob/master/test/natalie/method_test.rb

**Comment by richardboehme** [comment]
> Good find!
> 
> The argument handling is mostly confined to these two files:
> 
> * https://github.com/seven1m/natalie/blob/master/lib/natalie/compiler/method_args.rb
> * https://github.com/seven1m/natalie/blob/4a62b9d269679bde8f8ab89b54ae4e2b033cdd3e/src/natalie.cpp#L99-L175
> 
> With tests here:
> 
> https://github.com/seven1m/natalie/blob/master/test/natalie/method_test.rb

Thank you! I'm going to take a closer look at this 😄
