### ISSUE TITLE
Implement Enumerable::Lazy

### ISSUE THREAD

**Issue by richardboehme** [seven1m/natalie#83]
`Enumerable::Lazy` allows lazy chaining of some `Enumerable` methods.

The following methods have to be implemented:

- [x] chunk
- [x] chunk_while
- [x] collect
- [x] collect_concat
- [x] drop
- [x] drop_while
- [x] eager
- [x] enum_for
- [x] filter
- [x] filter_map
- [x] find_all
- [x] flat_map
- [x] force
- [x] grep
- [x] grep_v
- [x] lazy
- [x] map
- [x] reject
- [x] select
- [x] slice_after
- [x] slice_before
- [x] slice_when
- [x] take
- [x] take_while
- [x] to_a
- [x] to_enum
- [x] uniq
- [x] with_index
- [x] zip

**Comment by seven1m** [comment]
This was fully implemented by @richardboehme :tada:
