### ISSUE TITLE
Implement methods of Hash

### ISSUE THREAD

**Issue by seven1m** [seven1m/natalie#96]
Our main approach is to work on one spec from [ruby/spec](https://github.com/ruby/spec) at a time, implementing as much of the spec as possible, then check it off the list:

- [x] allocate_spec.rb
- [x] any_spec.rb
- [x] assoc_spec.rb
- [x] clear_spec.rb
- [x] clone_spec.rb
- [x] compact_spec.rb
- [x] compare_by_identity_spec.rb
- [x] constructor_spec.rb
- [x] deconstruct_keys_spec.rb
- [x] default_proc_spec.rb
- [x] default_spec.rb
- [x] delete_if_spec.rb
- [x] delete_spec.rb
- [x] dig_spec.rb
- [x] each_key_spec.rb
- [x] each_pair_spec.rb
- [x] each_spec.rb
- [x] each_value_spec.rb
- [x] element_reference_spec.rb
- [x] element_set_spec.rb
- [x] empty_spec.rb
- [x] eql_spec.rb
- [x] equal_value_spec.rb
- [x] except_spec.rb
- [x] fetch_spec.rb
- [x] fetch_values_spec.rb
- [x] filter_spec.rb
- [x] flatten_spec.rb
- [x] gte_spec.rb
- [x] gt_spec.rb
- [x] hash_spec.rb
- [x] has_key_spec.rb
- [x] has_value_spec.rb
- [x] include_spec.rb
- [x] index_spec.rb
- [x] initialize_spec.rb
- [x] inspect_spec.rb
- [x] invert_spec.rb
- [x] keep_if_spec.rb
- [x] key_spec.rb
- [x] keys_spec.rb
- [x] length_spec.rb
- [x] lte_spec.rb
- [x] lt_spec.rb
- [x] member_spec.rb
- [x] merge_spec.rb
- [x] new_spec.rb
- [x] rassoc_spec.rb
- [x] rehash_spec.rb
- [x] reject_spec.rb
- [x] replace_spec.rb
- [x] ruby2_keywords_hash_spec.rb
- [x] select_spec.rb
- [x] shift_spec.rb
- [x] size_spec.rb
- [x] slice_spec.rb
- [x] sort_spec.rb
- [x] store_spec.rb
- [x] to_a_spec.rb
- [x] to_hash_spec.rb
- [x] to_h_spec.rb
- [x] to_proc_spec.rb
- [x] to_s_spec.rb
- [x] transform_keys_spec.rb
- [x] transform_values_spec.rb
- [x] try_convert_spec.rb
- [x] update_spec.rb
- [x] values_at_spec.rb
- [x] value_spec.rb
- [x] values_spec.rb

**Comment by richardboehme** [comment]
This is finished now, right? I'd say we can close this 🎉

**Comment by seven1m** [comment]
Sweet!!!
